language: php

php:
  - 8.0

install:
  - composer self-update --2
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  - composer --version
  - composer clear-cache
#  - composer global require "fxp/composer-asset-plugin:@stable"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer update --prefer-dist

script:
  - composer test

#after_script:
#  - |
#    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
#      wget https://scrutinizer-ci.com/ocular.phar
#      php ocular.phar code-coverage:upload --format=php-clover ./code-coverage/coverage.clover
#    fi
